services:
- type: web
  name: todoboom-backend
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  envVars:
  - key: SECRET_KEY
    value: 2df80a9a2e5581e96f8b45c0c57d9bb89ef0aab1cc1e075a98dfb2811a1c5bfc
  - key: DATABASE_URL
    value: postgresql://neondb_owner:npg_VeRLr4OynqN3@ep-winter-sun-a1l9t0b5-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
  - key: FRONTEND_URL
    value: https://todo-app-phase2-two.vercel.app